Apparently git doesn't like symbolic links, using hardlinks instead.

diff --git a/backup b/backup
--- a/backup
+++ b/backup
@@ -1,1 +1,28 @@
-/home/egan/bin/backup
+#!/bin/bash
+
+##
+# backup -- rsync home directory to external hard disk
+#
+# usage -- backup
+#
+# notes -- pertinent partition must be mounted
+#
+# written -- 2008 by Egan McComb
+#
+# revised -- 11 July, 2009 by author
+##
+
+DSK=Pangolin
+DIR=arch-backup
+
+# Check that $DSK is mounted
+if mountpoint -q /media/$DSK
+then
+	# sync recursively, deleting old files
+	rsync -av --delete --exclude-from="/home/egan/.rsync/exclude" --include-from="/home/egan/.rsync/include" $HOME /media/$DSK/$DIR
+else
+	echo "Error: '$DSK' is not mounted"
+	exit 1
+fi
+
+exit 0
diff --git a/beep b/beep
--- a/beep
+++ b/beep
@@ -1,1 +1,88 @@
-/home/egan/bin/beep
+#!/bin/bash
+
+##
+# beep -- beep continuously or n times
+#
+# usage -- beep [-t NUMBER]
+#
+# written -- 27 July, 2010 by Egan McComb
+#
+# revised --
+##
+
+ERR_NARGS=3
+ERR_VARGS=5
+
+SNDFILE="$HOME/bin/.beep.wav"
+COMMAND="aplay"
+COPTION="$SNDFILE &>/dev/null"
+
+usage()
+{
+	echo "Usage: $(basename $0) [-t NUMBER]" >&2
+}
+
+chkargs()
+{
+	if [ -z "$1" ]
+	then
+		BCFUNCT="loop"
+	elif [ $1 = "-t" ]
+	then
+		if [ -z "$2" ]
+		then
+			echo "Error: Too few arguments" >&2
+			usage
+			exit $ERR_NARGS
+		elif $(echo $2 | grep -q [^[:digit:]])
+		then
+			echo "Error: Invalid NUMBER '$2'" >&2
+			usage
+			exit $ERR_VARGS
+		elif [ $# -gt 2 ]
+		then
+			echo "Error: Too many arguments" >&2
+			usage
+			exit $ERR_NARGS
+		else
+			BCFUNCT="loop $2"
+		fi
+	else
+		echo "Error: Invalid argument '$1'" >&2
+		usage
+		exit $ERR_VARGS
+	fi
+}
+
+loop()
+{
+	if [ -z "$1" ]
+	then
+		while true
+		do
+			eval $COMMAND $COPTION
+		done &
+		trap "kill $! && echo 'Caught SIGINT: Break'; exit 1" SIGINT SIGKILL
+		read -sn 1 $PRESS
+		kill $!
+	else
+		i=$1
+		while [ $i -gt 0 ]
+		do
+			eval $COMMAND $COPTION
+			let i-=1
+		done
+	fi
+}
+
+##----MAIN----##
+if [ ! -e $SNDFILE ]
+then
+	echo "Error: Missing resource '$SNDFILE'" >&2
+	exit 1
+fi
+
+chkargs $*
+$BCFUNCT
+
+exit 0
diff --git a/blog b/blog
--- a/blog
+++ b/blog
@@ -1,1 +1,48 @@
-/home/egan/bin/blog
+#!/bin/bash
+
+##
+# blog -- obtain fresh blender commit logs and view them.
+#
+# usage -- blog
+#
+# notes -- more repositories can be added as cases for $1
+#	   will ultimately be replaced with svnnew
+#
+# written -- 1 March, 2009 by Egan McComb
+#
+# revised -- 11 July, 2009 by author
+##
+
+ERR_NARGS=3
+ERR_VARGS=5
+
+BTK=$HOME/src/blender/blender
+
+NFILE=".svn/revision.info"
+
+if [ $# -lt 2 ]
+then
+	case "$1" in
+		'')		cd $BTK;;
+		*)		echo "Error: Not a valid repository '$1'" >&2
+				exit $ERR_VARGS;;
+	esac
+else
+	echo "Error: Too many arguments" >&2
+	exit $ERR_NARGS
+fi
+
+if [ ! -s $NFILE ]
+then
+	echo "Error: Data file does not exist or is empty: Creating" >&2
+	echo -n "Enter a revison number to begin: " >&2
+	read RESPONSE
+	echo $RESPONSE > $NFILE
+	echo "Created $PWD/revision.info" >&2
+fi
+
+READ=$(cat $NFILE)
+svn log --incremental -r $(( $READ + 1 )):BASE | less
+svn info | sed -n '5p' | cut -d " " -f 2 | sponge $NFILE
+
+exit 0
diff --git a/catpdf b/catpdf
--- a/catpdf
+++ b/catpdf
@@ -1,1 +1,56 @@
-/home/egan/bin/catpdf
+#!/bin/bash
+
+##
+# catpdf -- cat pdfs together with ghostscript
+#
+# usage -- catpdf OUTFILE INFILES
+#
+# written -- 6 June, 2011 by Egan McComb
+#
+# revised --
+##
+
+ERR_NARGS=3
+ERR_VARGS=5
+
+COMMAND="gs -dBATCH -dNOPAUSE -q -sDEVICE=pdfwrite"
+
+usage()
+{
+	echo "Usage: $(basename $0) OUTFILE INFILES" >&2
+}
+
+chkargs()
+{
+	if [ $# -lt 3 ]
+	then
+		echo "Error: Too few arguments" >&2
+		usage
+		exit $ERR_NARGS
+	fi
+	if [ -f $1 ]
+	then
+		echo "Warning: Output file exists" >&2
+		echo -n "Continue? [y/N] " >&2
+		read RESPONSE
+		if [ "$RESPONSE" != "y" ]
+		then
+			exit 1
+		fi
+	fi
+	OUT="$1"
+	shift
+	for FILE in "$@"
+	do
+		if [ ! -e "$FILE" ]
+		then
+			echo "Error: Invalid file '$FILE'" >&2
+			exit $ERR_VARGS
+		fi
+	done
+}
+
+##----MAIN----##
+chkargs "$@"
+$COMMAND  -sOutputFile="$OUT" "$@"
+exit 0
diff --git a/esplit b/esplit
--- a/esplit
+++ b/esplit
@@ -1,1 +1,103 @@
-/home/egan/bin/esplit
+#!/bin/bash
+
+##
+# esplit -- split a file into pieces
+#
+# usage -- esplit -m | -c COUNT [FILE ...]
+#
+# written -- 27 May, 2009 by Egan McComb
+#
+# revised -- 12 July, 2009 by author
+##
+
+ERR_NARGS=3
+ERR_VARGS=5
+
+SIZE=16777216
+
+usage()
+{
+	echo "Usage: $(basename $0) -m | -c COUNT FILE..." >&2
+}
+
+chkargs()
+{
+	if [ $# -lt 2 ]
+	then
+		echo "Error: Too few arguments" >&2
+		usage
+		exit $ERR_NARGS
+	elif [ ! $1 = "-m" ] && [ ! $1 = "-c" ]
+	then
+		echo "Error: Invalid argument '$1'" >&2
+		usage
+		exit $ERR_VARGS
+	fi
+}
+
+chkfile()
+{
+	if [ ! -e "$1" ]
+	then
+		echo "Error: Nonexistant file '$1'" >&2
+		echo "Skipping..." >&2
+		continue
+	elif [ ! -f "$1" ]
+	then
+		echo "Error: Bad file '$1'" >&2
+		echo "Skipping..." >&2
+		continue
+	fi
+}
+
+methodc()
+{
+	if [ "$1" = "-m" ]
+	then
+		METHOD=magic
+		NSHIFT=shift
+	else
+		METHOD=nsplit
+		if [ -z "$2" ]
+		then
+			echo "Error: Too few arguments" >&2
+			usage
+			exit $ERR_NARGS
+		elif $(grep -q [^[:digit:]] <<< $2)
+		then
+			echo "Error: Invalid argument '$2'" >&2
+			usage
+			exit $ERR_VARGS
+		else
+			METHOD="nsplit $2"
+			NSHIFT="shift && shift"
+		fi
+	fi
+}
+
+
+magic()
+{
+	split -b $SIZE "$1" "$1".
+	echo "Split file $FILE into pieces of $SIZE bytes"
+}
+
+nsplit()
+{
+	FSIZE=$(command ls -l "$2" | cut -d " " -f 5)
+	SSIZE=$(($FSIZE/$1))
+	split -b $SSIZE "$2" "$2".
+	echo "Split file $2 into $1 pieces of $SSIZE bytes"
+}
+
+###----MAIN----###
+chkargs "$@"
+methodc "$@"
+$NSHIFT
+for FILE in "$@"
+do
+	chkfile "$FILE"
+	$METHOD "$FILE"
+done
+
+exit 0
diff --git a/gweather b/gweather
--- a/gweather
+++ b/gweather
@@ -1,1 +1,63 @@
-/home/egan/bin/gweather
+#!/bin/bash
+
+##
+# gweather -- obtain weather data using google api
+#
+# usage -- gweather [-c|--current]|[-f|--forecast][LOCID]
+#
+# note -- no protection against invalid LOCID
+#
+# written -- 12 September, 2010 by Egan McComb
+#
+# revised --
+##
+
+ERR_NARGS=3
+ERR_VARGS=5
+
+CURRENT="$HOME/bin/.current.xslt"
+FORECAST="$HOME/bin/.forecast.xslt"
+LOCID="Mountain+View"
+
+usage()
+{
+	echo "Usage: $(basename $0) [-c|--current]|[-f|--forecast] [LOCID]" >&2
+	echo -e "\t-When unspecified, LOCID=$LOCID" >&2
+	echo -e "\t-LOCID can be given as a string or zip code" >&2
+}
+
+chkargs()
+{
+	if [ $# == 0 ]
+	then
+		echo "Error: Too few arguments" >&2
+		usage
+		exit $ERR_NARGS
+
+	elif [ $1 = "-f" ] || [ $1 = "--forecast" ]
+	then
+		FILTER=$FORECAST
+	elif [ $1 = "-c" ] || [ $1 = "--current" ]
+	then
+		FILTER=$CURRENT
+	elif [ $# -gt 1 ]
+	then
+		echo "Error: Too many arguments" >&2
+		usage
+		exit $ERR_NARGS
+	else
+		echo "Error: Invalid arguments" >&2
+		usage
+		exit $ERR_VARGS
+	fi
+	if [ ! -z "$2" ]
+	then
+		LOCID="$2"
+	fi
+}
+
+##----MAIN---##
+chkargs "$@"
+curl -s http://www.google.com/ig/api?weather="$LOCID" | xsltproc $FILTER -
+
+exit 0
diff --git a/imgur b/imgur
--- a/imgur
+++ b/imgur
@@ -1,1 +1,77 @@
-/home/egan/bin/imgur
+#!/bin/bash
+
+##
+# imgur -- upload image to imgur.com
+#
+# usage -- imgur FILE
+#
+# notes -- stores history in ~/bin/.imgur_history
+#
+# todo -- thumbnail link?
+#
+# written -- 25 August, 2010 by Egan McComb
+#
+# revised --
+##
+
+ERR_NARGS=3
+ERR_VARGS=5
+
+APIKEY="4f22353fbb8473a442bf708ecd553ffb"
+
+HFILE="$HOME/bin/.imgur_history"
+
+usage()
+{
+	echo "Usage: $(basename $0) FILE" >&2
+}
+
+chkargs()
+{
+	if [ $# -ne 1 ]
+	then
+		if [ $# == 0 ]
+		then
+			echo "Error: Too few arguments" >&2
+			usage
+			exit $ERR_NARGS
+		else
+			echo "Error: Too many arguments" >&2
+			usage
+			exit $ERR_NARGS
+		fi
+	elif [ ! -f "$1" ]
+	then
+		echo "Error: Invalid file '$1'" >&2
+		usage
+		exit $ERR_VARGS
+	else
+		IMAGE="$1"
+	fi
+}
+
+##----MAIN----##
+chkargs "$@"
+
+RESPONSE=$(curl -sF "key=$APIKEY" -F "image=@$IMAGE" http://imgur.com/api/upload.xml)
+
+if [ $? -ne 0 ]
+then
+	echo "Upload failed" >&2
+	exit 1
+elif [ $(grep -c "<error_msg>" <<< $RESPONSE) -gt 0 ]
+then
+	echo "Error: imgur says:" >&2
+	echo $RESPONSE | sed -r 's/.*<error_msg>(.*)<\/error_msg>.*/\1/' >&2
+	exit 1
+fi
+
+IURL=$(sed -r 's/.*<original_image>(.*)<\/original_image>.*/\1/' <<< $RESPONSE)
+DURL=$(sed -r 's/.*<delete_page>(.*)<\/delete_page>.*/\1/' <<< $RESPONSE)
+
+echo -n "$IURL" | xclip
+date +%T\ on\ %D >> $HFILE
+echo "$IURL" | tee -a $HFILE
+echo "$DURL" >> $HFILE
+
+exit 0
diff --git a/lnmv b/lnmv
--- a/lnmv
+++ b/lnmv
@@ -1,1 +1,53 @@
-/home/egan/bin/lnmv
+#!/bin/bash
+
+##
+# lnmv -- replace a file with a symbolic link to its new location
+#
+# usage -- lnmv OLDFILE NEWFILE
+#
+# written -- 7 April, 2011 by Egan McComb
+#
+# revised --
+##
+
+ERR_NARGS=3
+ERR_VARGS=5
+
+usage()
+{
+	echo "Usage: $(basename $0) OLDFILE NEWFILE" >&2
+	echo -e "\t-Note: The new filename must be given" >&2
+	echo -e "\t       even if it is not to be renamed." >&2
+}
+
+chkargs()
+{
+	if [ $# -ne 2 ]
+	then
+		echo "Error: Wrong number of arguments" >&2
+		usage
+		exit $ERR_NARGS
+	fi
+	if [ -d "$2" ]
+	then
+		echo "Error: Invalid filename '$2'">&2
+		usage
+		exit $ERR_VARGS
+	fi
+}
+
+##----MAIN----##
+chkargs "$@"
+
+OLDFILE="$1"
+NEWFILE=$(readlink -f "$2")
+
+mv "$1" "$2" && ln -s "$NEWFILE" "$OLDFILE"
+
+if [ $? -ne 0 ]
+then
+	echo "Error: Unable to make link." >&2
+	exit 1
+fi
+
+exit 0
diff --git a/mkoff b/mkoff
--- a/mkoff
+++ b/mkoff
@@ -1,1 +1,64 @@
-/home/egan/bin/mkoff
+#!/bin/bash
+
+##
+# mkoff -- prepare a website for offline use
+#
+# usage -- mkoff -s STRING [FILE]
+#
+# notes -- obviously the resources should be downloaded
+#
+# written -- 4 July, 2009 by Egan McComb
+##
+
+ERR_NARGS=3
+ERR_NARGS=5
+
+usage()
+{
+	echo "Usage: $(basename $0) -s STRING [FILE]" >&2
+}
+
+chkfile()
+{
+	if [ -z "$1" ]
+	then
+		echo "Error: Too few arguments" >&2
+		usage
+		exit $ERR_NARGS
+	elif [ ! -e "$1" ]
+	then
+		echo "Error: Nonexistent file: $1" >&2
+		usage
+		exit $ERR_VARGS
+	elif [ ! -f "$1" ]
+	then
+		echo "Error: Wrong type of file: $1" >&2
+		usage
+		exit $ERR_VARGS
+	else
+		FILE="$1"
+	fi
+}
+
+##----MAIN----##
+
+if [ $1 = "-s" ]
+then
+	if [ ! -z "$2" ]
+	then
+		STRING="$2"
+		chkfile "$3"
+		cp "$FILE" "$FILE"~
+		sed "s|${STRING}||g" "$FILE" | sponge "$FILE"
+	else
+		echo "Error: Too few arguments" >&2
+		usage
+		exit $ERR_NARGS
+	fi
+else
+	chkfile "$1"
+	cp "$FILE" "$FILE"~
+	perl -p0e 's|<a href="(.*://.*?/)(.*")|<a href="./$2|g' "$FILE" | sponge "$FILE"
+fi
+
+exit 0
diff --git a/mkwcfg b/mkwcfg
--- a/mkwcfg
+++ b/mkwcfg
@@ -1,1 +1,113 @@
-/home/egan/bin/mkwcfg
+#!/bin/bash
+
+##
+# mkwcfg -- creates wireless network profile
+#
+# usage -- wconn ESSID [TYPE] [KEY]
+#
+# todo -- autodetect network type and prompt for key
+#
+# written -- 1 January, 2011 by Greg Dwulet
+#
+# revised -- 13 March, 2011 by Egan McComb
+##
+
+ERR_NARGS=3
+ERR_VARGS=5
+
+NETDIR="/etc/network.d"
+
+usage()
+{
+	echo "Usage: $(basename $0) ESSID [wep|wpa] [KEY]" >&2
+}
+
+chkargs()
+{
+	if [ -z "$1" ]
+	then
+		echo "Error: Too few arguments" >&2
+		usage
+		exit $ERR_NARGS
+	elif [ $# -gt 3 ]
+	then
+		echo "Error: Too many arguments" >&2
+		usage
+		exit $ERR_NARGS
+	fi
+}
+
+doargs()
+{
+	if [ $# -eq 1 ]
+	then
+		if $(sudo iwlist wlan0 scan | piwlist.py | grep -q "$1")
+		then
+			ESSID="$1"
+			FILE="$NETDIR/$ESSID-wireless"
+		else
+			echo "Error: Unknown wireless network '$1'" >&2
+			usage
+			exit $ERR_VARGS
+		fi
+	elif [ $# -eq 2 ]
+	then
+		echo "Error: Incorrect arguments" >&2
+		usage
+		exit $ERR_VARGS
+	else
+		if [ $2 != "wep" ] && [ $2 != "wpa" ]
+		then
+			echo "Error: Invalid network type '$2'" >&2
+			usage
+			exit $ERR_VARGS
+		else
+			TYPE=$2
+			KEY="$3"
+		fi
+		if $(sudo iwlist wlan0 scan | piwlist.py | grep -q "$1")
+		then
+			ESSID="$1"
+			FILE="$NETDIR/$ESSID-wireless"
+		else
+			echo "Error: Unknown wireless network '$1'" >&2
+			usage
+			exit $ERR_NARGS
+		fi
+	fi
+}
+
+makeprofile()
+{
+	if [ ! -e "$FILE" ]
+	then
+		cp $NETDIR/examples/wireless-$TYPE "$FILE"
+		editprofile "$ESSID" $TYPE "$KEY"
+	fi
+}
+
+editprofile()
+{
+	sed -i "s/MyNetwork/$ESSID/" "$FILE"
+	if [ $TYPE = "wep" ]
+	then
+		sed -i "s/123456789/$KEY/" "$FILE"
+	elif [ $TYPE = "wpa" ]
+	then
+		sed -i "s/WirelessKey/$KEY/" "$FILE"
+	fi
+	echo "DHCP_TIMEOUT='3000'" >> "$FILE"
+}
+
+##----MAIN----##
+if [ $EUID != "0" ]
+then
+	echo "Error: Must be root"
+	exit 1
+fi
+
+chkargs "$@"
+doargs "$@"
+makeprofile
+
+exit 0
diff --git a/svnnew b/svnnew
--- a/svnnew
+++ b/svnnew
@@ -1,1 +1,28 @@
-/home/egan/bin/svnnew
+#!/bin/bash
+
+##
+# svnnew -- obtain fresh svn commit logs and view them
+#
+# usage -- svnlog
+#
+# notes -- finds last revision in file $PWD/.svn/revision.info
+#
+# written -- 1 March 2009 by Egan McComb
+#
+# revised -- 22 August, 2010 by author
+##
+
+NFILE=".svn/revision.info"
+LFILE=".svn/revision.log"
+
+if [ ! -s $NFILE ]
+then
+	echo "Error: No revision file found, exiting" >&2
+	exit 1
+fi
+
+READ=$(cat $NFILE)
+svn log --incremental -r $(( $READ + 1 )):BASE | tee -a $LFILE | less
+svn info | sed -n '5p' | cut -d " " -f 2 | sponge $NFILE
+
+exit 0
diff --git a/svnup b/svnup
--- a/svnup
+++ b/svnup
@@ -1,1 +1,86 @@
-/home/egan/bin/svnup
+#!/bin/bash
+
+##
+# svnup -- sync svn source trees to svn server
+#
+# usage -- svnup [-h|--help]|[-o|--only][DIR...]
+#
+# notes -- default repos are newline-delimited in ~/bin/.svnlist
+#
+# written -- 2008 by Egan McComb
+#
+# revised -- 22 August, 2010 by author
+##
+
+IFS=":"
+ERR_VARGS=5
+
+LFILE="$HOME/bin/.svnlist"
+SLINE="\E[01;34m::\033[0m Updating:"
+TLINE="\E[01;34m>\033[0m"
+
+usage()
+{
+	echo "Usage: $(basename $0) [-h|--help]|[-o|--only][DIR...]" >&2
+	echo -e "\t-Directory arguments are concatenated" >&2
+	echo -e "\t to newline-delimited default list $LFILE" >&2
+	echo -e "\t unless the '-o' option is passed" >&2
+}
+
+chkfile()
+{
+	if [ ! -d "$1" ]
+	then
+		echo "Error: Nonexistent directory '$1'" >&2
+		exit $ERR_VARGS
+	else
+		if [ ! -d "$1"/.svn ]
+		then
+			echo "Error: Invalid svn repo '$1'" >&2
+			exit $ERR_VARGS
+		fi
+	fi
+}
+
+chkargs()
+{
+	if [ $# -ne 0 ]
+	then
+		if [ $1 = "-h" ] || [ $1 = "--help" ]
+		then
+			usage
+			exit 0
+		elif [ $1 = "-o" ] || [ $1 = "--only" ]
+		then
+			shift
+			for ARG in "$@"
+			do
+				chkfile "$ARG"
+				REPOS="$REPOS $ARG"
+			done
+		else
+			REPOS="$(cat $LFILE | tr '\n' ' ')"
+			for ARG in "$@"
+			do
+				chkfile "$ARG"
+				REPOS="$REPOS $ARG"
+			done
+		fi
+	else
+		REPOS=$(cat $LFILE | tr '\n' ':')
+	fi
+}
+
+##----MAIN----##
+chkargs "$@"
+
+for DIR in "$REPOS"
+do
+	echo -e "$SLINE ${DIR/\/home\/egan/~}"
+	cd "$DIR" && svn up && cd
+	echo -ne "$TLINE "
+	date +%T\ on\ %D
+	echo
+done
+
+exit 0
diff --git a/swap b/swap
--- a/swap
+++ b/swap
@@ -1,1 +1,49 @@
-/home/egan/bin/swap
+#!/bin/bash
+
+##
+# trade -- swap file names
+#
+# usage -- swap FILE1 FILE2
+#
+# written -- 12 Dec, 2009 by Egan McComb
+#
+# revised -- 25 Dec, 2010 by author
+##
+
+ERR_NARGS=3
+ERR_VARGS=5
+
+usage()
+{
+	echo "Usage: $(basename $0) FILE1 FILE2" >&2
+}
+
+chkargs()
+{
+	if [ $# -ne 2 ]
+	then
+		echo "Error: Wrong number of arguments" >&2
+		usage
+		exit $ERR_NARGS
+	fi
+}
+
+chkfile()
+{
+	for FILE in "$@"
+	do
+		if [ ! -e "$1" ]
+		then
+			echo "Error: File '$1' does not exist" >&2
+			usage
+			exit $ERR_VARGS
+		fi
+	done
+}
+
+##----MAIN----##
+chkargs "$@"
+chkfile "$@"
+
+TEMP=$(mktemp swap.XXX)
+mv "$1" $TEMP && mv "$2" "$1" && mv $TEMP "$2" && exit 0
diff --git a/tablize b/tablize
--- a/tablize
+++ b/tablize
@@ -1,1 +1,79 @@
-/home/egan/bin/tablize
+#!/bin/bash
+
+##
+# tablize -- convert labeled tsv files to latex tables
+#
+# usage -- tablize [FILE ...]
+#
+# written -- 30 April, 2010 by Egan McComb
+#
+# revised --
+##
+
+ERR_NARGS=3
+ERR_VARGS=5
+
+TE="tabular"
+CS=" l |"
+
+usage()
+{
+	echo "$(basename $0) [FILE ...]" >&2
+}
+
+chkargs()
+{
+	if [ -z "$1" ]
+	then
+		echo "Error: Too few arguments" >&2
+		usage
+		exit $ERR_NARGS
+	fi
+}
+
+chkfile()
+{
+	if [ ! -e "$1" ]
+	then
+		echo "Error: Invalid file: '$1'" >&2
+		usage
+		exit $ERR_VARGS
+	fi
+}
+
+name()
+{
+	IN="$1"
+	OUT=$(sed 's/\..*$/.tex/' <<< $IN)
+}
+
+column()
+{
+	NF=$(awk 'END{printf "%s", NF}' < $IN)
+	CSP=" |"$CS
+	i="1"
+	while [ $i -lt $NF ]
+	do
+		CSP=${CSP}$CS
+		let i+=1
+	done
+}
+
+convert()
+{
+	echo -e "\\\begin{$TE}{$CSP }\n\\hline" > $OUT
+	sed "s/	/ \& /g;s/$/ \\\\\\\\\n\\\\hline/g" < $1 >> $OUT
+	echo "\end{$TE}" >> $OUT
+}
+
+##---MAIN---##
+chkargs "$@"
+for FILE in "$@"
+do
+	chkfile "$FILE"
+	name "$FILE"
+	column "$FILE"
+	convert "$FILE"
+done
+
+exit 0
diff --git a/tex2img b/tex2img
--- a/tex2img
+++ b/tex2img
@@ -1,1 +1,116 @@
-/home/egan/bin/tex2img
+#!/bin/bash
+
+##
+# tex2img -- quickly get png output from latex code (for math)
+#
+# usage -- tex2img [SIZE] STRING
+#
+# notes -- not many measures to prevent stupidity are in place
+#
+# written -- 25 August, 2010 by Egan McComb
+#
+# revised --
+##
+
+ERR_NARGS=3
+ERR_VARGS=5
+
+FILE=$(mktemp $(basename $0).XXX.tex)
+SIZE="\LARGE"
+LCOMMAND="latex -interaction=batchmode"
+DCOMMAND="dvipng -q -T tight -o ${FILE/%tex/png}"
+
+usage()
+{
+	echo "Usage: $(basename $0) [SIZE] STRING" >&2
+	echo -e "\t-SIZE is standard LaTeX size command name" >&2
+	echo -e "\t without any substring 'size'" >&2
+	echo -e "\t-Few measures preventing stupidity" >&2
+	echo -e "\t are in place" >&2
+	echo -e "\t-Single-quoting is recommended" >&2
+}
+
+chkargs()
+{
+	if [ $# -eq 0 ]
+	then
+		echo "Error: Too few arguments" >&2
+		usage
+		exit $ERR_NARGS
+	elif [ $# -eq 2 ]
+	then
+		case $1 in
+			tiny)
+				SIZE="\tiny";;
+			script)
+				SIZE="\scriptsize";;
+			footnote)
+				SIZE="\footnotesize";;
+			small)
+				SIZE="\small";;
+			normal)
+				SIZE="\normal";;
+			large)
+				SIZE="\large";;
+			Large)
+				SIZE="\Large";;
+			LARGE)
+				SIZE="\LARGE";;
+			huge)
+				SIZE="\huge";;
+			Huge)
+				SIZE="\Huge";;
+			*)
+				echo "Error: Invalid argument '$1'" >&2
+				usage
+				exit $ERR_VARGS
+		esac
+		TEXT="$2"
+	elif [ $# -gt 2 ]
+	then
+		echo "Error: Too many arguments" >&2
+		usage
+		exit $ERR_NARGS
+	else
+		TEXT="$*"
+	fi
+}
+
+convert()
+{
+	$LCOMMAND $FILE > /dev/null
+	if [ $? -ne 0 ]
+	then
+		echo "Error: Unable to compile LaTeX code" >&2
+		exit 1
+	fi
+	$DCOMMAND ${FILE/%tex/dvi} > /dev/null
+}
+
+clean()
+{
+	rm -f ${FILE/%tex/aux} ${FILE/%tex/dvi} ${FILE/%tex/log} $FILE
+}
+
+##----MAIN----##
+chkargs $*
+cat > $FILE <<- EOF
+	\documentclass{article}
+	\usepackage[american]{babel}
+	\usepackage{amsmath}
+	\usepackage{amssymb}
+	\usepackage{amsfonts}
+	\pagestyle{empty}
+	\newcommand{\abs}[1]{\lvert#1\rvert}
+	\newcommand{\s}{\Rightarrow}
+	\begin{document}
+	$SIZE
+	\$\$${TEXT}\$\$
+	\end{document}
+	EOF
+convert
+clean
+
+echo "${FILE/%tex/png}"
+
+exit 0
diff --git a/turl b/turl
--- a/turl
+++ b/turl
@@ -1,1 +1,54 @@
-/home/egan/bin/turl
+#!/bin/bash
+
+##
+# turl -- shorten a url using tinyurl.com
+#
+# usage -- turl URL
+#
+# notes -- watch out for problematic characters
+#
+# todo -- accept stdin
+#
+# written -- 4 July 2010 by Egan McComb
+#
+# revised -- 7 July 2010 by author
+##
+
+ERR_NARGS=3
+
+COMMAND="wget"
+COPTION=" -q -O -"
+PSTDATA='--post-data="url=$URL"'
+SERVICE="http://tinyurl.com/create.php"
+
+usage()
+{
+	echo "Usage: $(basename $0) URL" >&2
+	echo -e "\t-Watch out for ampersands" >&2
+}
+
+chkargs()
+{
+	if [ -z "$1" ]
+	then
+		echo "Error: Too few arguments" >&2
+		usage
+		exit $ERR_NARGS
+	elif [ $# -gt 1 ]
+	then
+		echo "Error: Too many arguments" >&2
+		usage
+		exit $ERR_NARGS
+	else
+		URL="$1"
+	fi
+}
+
+##----MAIN----##
+chkargs "$@"
+
+OUT=$(eval $COMMAND $COPTION $PSTDATA $SERVICE | sed -n 's/.*\(http:\/\/tinyurl.com\/[a-z0-9][a-z0-9]*\).*/\1/p' | uniq)
+echo -n $OUT | xclip
+echo $OUT
+
+exit 0
diff --git a/volume b/volume
--- a/volume
+++ b/volume
@@ -1,1 +1,85 @@
-/home/egan/bin/volume
+#!/bin/bash
+
+##
+# volume -- control alsa mixer levels
+#
+# usage -- volume [[toggle|up|down|level LEVEL]|[t|u|d|l LEVEL]]
+#
+# written -- 30 July, 2009 by Egan McComb
+#
+# revised -- 15 June, 2010 by author
+##
+
+ERR_NARGS=3
+ERR_VARGS=5
+
+COMMAND="amixer"
+COPTION=" -q set"
+SDEVICE="Master"
+VOLSTEP=3
+
+usage()
+{
+	echo "Usage: $(basename $0) [[toggle|up|down|level LEVEL]|[t|u|d|l LEVEL]]" >&2
+	echo -e "\t-With no arguments, print volume level" >&2
+	echo -e "\t-Default step for up/down is $VOLSTEP%" >&2
+	echo -e "\t as indicated in $0" >&2
+	echo -e "\t-LEVEL is given as a percentage" >&2
+	echo -e "\t-Complex volume control can be done with alsamixer" >&2
+}
+
+chkargs()
+{
+	if [ $# -gt 1 ] && [ $1 != "level" ] && [ $1 != "l" ]
+	then
+		echo "Error: Too many arguments" >&2
+		usage
+		exit $ERR_NARGS
+	fi
+}
+
+doargs()
+{
+	if [ -z "$1" ]
+	then
+		STATE=$($COMMAND | grep -A 4 \'$SDEVICE\' | awk {'print $6'} | grep -m 1 "\[on\]\|\[off\]" | sed -e 's/[][]//g;s/o/O/')
+		VOLUME=$($COMMAND | grep -A 6 \'$SDEVICE\' | awk {'print $4'} | grep -m 1 % | sed -e 's/[][]//g')
+		printf "%-4s %3s\n" "$STATE:" $VOLUME
+		exit 0
+	elif [ $1 = "toggle" ] || [ $1 = "t" ]
+	then
+		ARG="$SDEVICE toggle"
+	elif [ $1 = "up" ] || [ $1 = "u" ]
+	then
+		ARG="$SDEVICE ${VOLSTEP}%+"
+	elif [ $1 = "down" ] || [ $1 = "d" ]
+	then
+		ARG="$SDEVICE ${VOLSTEP}%-"
+	elif [ $1 = "level" ] || [ $1 = "l" ]
+	then
+		if [ -z "$2" ]
+		then
+			echo "Error: Too few arguments" >&2
+			usage
+			exit $ERR_NARGS
+		elif  $(grep -q [^[:digit:]] <<< $2) || [ $2 -gt 100 ]
+		then
+			echo "Error: Invalid LEVEL '$2'" >&2
+			usage
+			exit $ERR_VARGS
+		fi
+		ARG="$SDEVICE ${2}%"
+	else
+		echo "Error: Invalid argument '$1'" >&2
+		usage
+		exit $ERR_VARGS
+	fi
+}
+
+##----MAIN----##
+chkargs $*
+doargs $*
+
+$COMMAND $COPTION $ARG
+
+exit 0
