Style revision: use lowercase parameters.

diff --git a/beep b/beep
--- a/beep
+++ b/beep
@@ -10,13 +10,13 @@
 # revised --
 ##
 
-ERR_NARGS=3
-ERR_VARGS=5
+err_nargs=3
+err_vargs=5
 
-SNDFILE="$HOME/bin/.beep.wav"
-COMMAND="aplay"
-COPTION="$SNDFILE &>/dev/null"
-SDEVICE="Master"
+sndfile="$HOME/bin/.beep.wav"
+command="aplay"
+coption="$SNDFILE &>/dev/null"
+sdevice="Master"
 
 usage()
 {
@@ -27,31 +27,31 @@ chkargs()
 {
 	if [ -z "$1" ]
 	then
-		BCFUNCT="loop"
+		bcfunct="loop"
 	elif [ $1 = "-t" ]
 	then
 		if [ -z "$2" ]
 		then
 			echo "Error: Too few arguments" >&2
 			usage
-			exit $ERR_NARGS
+			exit $err_nargs
 		elif $(echo $2 | grep -q [^[:digit:]])
 		then
 			echo "Error: Invalid NUMBER '$2'" >&2
 			usage
-			exit $ERR_VARGS
+			exit $err_vargs
 		elif [ $# -gt 2 ]
 		then
 			echo "Error: Too many arguments" >&2
 			usage
-			exit $ERR_NARGS
+			exit $err_nargs
 		else
-			BCFUNCT="loop $2"
+			bcfunct="loop $2"
 		fi
 	else
 		echo "Error: Invalid argument '$1'" >&2
 		usage
-		exit $ERR_VARGS
+		exit $err_vargs
 	fi
 }
 
@@ -61,7 +61,7 @@ loop()
 	then
 		while true
 		do
-			eval $COMMAND $COPTION
+			eval $command $coption
 		done &
 		trap "kill $! && echo 'Caught SIGINT: Break'; exit 1" SIGINT SIGKILL
 		read -sn 1
@@ -70,7 +70,7 @@ loop()
 		i=$1
 		while [ $i -gt 0 ]
 		do
-			eval $COMMAND $COPTION
+			eval $command $coption
 			let i-=1
 		done
 	fi
@@ -78,21 +78,21 @@ loop()
 
 unmute()
 {
-	if $(amixer | grep -A 4 \'$SDEVICE\' | awk {'print $6'} | grep -q  "\[off\]")
+	if $(amixer | grep -A 4 \'$sdevice\' | awk {'print $6'} | grep -q  "\[off\]")
 	then
-		amixer -q set $SDEVICE toggle
+		amixer -q set $sdevice toggle
 	fi
 }
 
 ##----MAIN----##
-if [ ! -e $SNDFILE ]
+if [ ! -e $sndfile ]
 then
-	echo "Error: Missing resource '$SNDFILE'" >&2
+	echo "Error: Missing resource '$sndfile'" >&2
 	exit 1
 fi
 
 chkargs $*
 unmute
-$BCFUNCT
+$bcfunct
 
 exit 0
diff --git a/catpdf b/catpdf
--- a/catpdf
+++ b/catpdf
@@ -10,10 +10,10 @@
 # revised -- 19 December, 2011 by author
 ##
 
-ERR_NARGS=3
-ERR_VARGS=5
+err_nargs=3
+err_vargs=5
 
-COMMAND="gs -dBATCH -dNOPAUSE -q -sDEVICE=pdfwrite"
+command="gs -dBATCH -dNOPAUSE -q -sDEVICE=pdfwrite"
 
 usage()
 {
@@ -26,30 +26,30 @@ chkargs()
 	then
 		echo "Error: Too few arguments" >&2
 		usage
-		exit $ERR_NARGS
+		exit $err_nargs
 	fi
 	if [ -f "${!#}" ]
 	then
 		echo "Warning: Output file exists" >&2
 		echo -n "Continue? [y/N] " >&2
-		read RESPONSE
-		if [ "$RESPONSE" != "y" ]
+		read response
+		if [ "$response" != "y" ]
 		then
 			exit 1
 		fi
 	fi
-	OUT="${!#}"
-	for FILE in "${@:1:$(($#-1))}"
+	out="${!#}"
+	for file in "${@:1:$(($#-1))}"
 	do
-		if [ ! -e "$FILE" ]
+		if [ ! -e "$file" ]
 		then
-			echo "Error: Invalid file '$FILE'" >&2
-			exit $ERR_VARGS
+			echo "Error: Invalid file '$file'" >&2
+			exit $err_vargs
 		fi
 	done
 }
 
 ##----MAIN----##
 chkargs "$@"
-$COMMAND  -sOutputFile="$OUT" "${@:1:$(($#-1))}"
+$command  -sOutputFile="$out" "${@:1:$(($#-1))}"
 exit 0
diff --git a/excpdf b/excpdf
--- a/excpdf
+++ b/excpdf
@@ -10,11 +10,11 @@
 # revised --
 ##
 
-ERR_NARGS=3
-ERR_VARGS=5
+err_nargs=3
+err_vargs=5
 
-TRIMCOM="tr ':\-,' '\n'"
-COMMAND="gs -dBATCH -dNOPAUSE -q -sDEVICE=pdfwrite"
+trimcom="tr ':\-,' '\n'"
+command="gs -dBATCH -dNOPAUSE -q -sDEVICE=pdfwrite"
 
 usage()
 {
@@ -30,20 +30,20 @@ chkargs()
 	then
 		echo "Error: Wrong number of arguments" >&2
 		usage
-		exit $ERR_NARGS
+		exit $err_nargs
 	fi
-	chkfile "$2" && IN="$2"
-	OUT="$3"
-	if $(grep -q "[^[:digit:]:-]" <<< "$1") && $(grep -q "[^[:digit:],]" <<< "$1")
+	chkfile "$2" && in="$2"
+	out="$3"
+	if $(grep -q "[^[:digit:]:-]" <<< "$1")
 	then
 		echo "Error: Invalid page range syntax" >&2
 		usage
-		exit $ERR_VARGS
-	elif ! $(sort -nC <(eval $TRIMCOM <<< $1)) || [ ! -z $(uniq -d <(eval $TRIMCOM <<< $1)) ]
+		exit $err_vargs
+	elif ! $(sort -nC <(eval $trimcom <<< $1)) || [ ! -z $(uniq -d <(eval $trimcom <<< $1)) ]
 	then
 		echo "Error: Invalid page range collation" >&2
 		usage
-		exit $ERR_VARGS
+		exit $err_vargs
 	fi
 }
 
@@ -52,31 +52,31 @@ chkfile()
 	if [ ! -f "$1" ] || ! $(grep -q "PDF" <<< $(file "$1"))
 	then
 		echo "Error: Invalid input file '$1'" >&2
-		exit $ERR_VARGS
+		exit $err_vargs
 	fi
 }
 
 range()
 {
 	IFS=":"
-	RANGES=($@)
-	TFILES=()
-	for RANGE in ${RANGES[@]}
+	ranges=($@)
+	tfiles=()
+	for range in ${ranges[@]}
 	do
-		if [ $(awk 'BEGIN { FS="-"} ; { print NF }' <<< $RANGE) -gt 2 ]
+		if [ $(awk 'BEGIN { FS="-"} ; { print NF }' <<< $range) -gt 2 ]
 		then
-			echo "Error: Invalid subrange '$RANGE'" >&2
+			echo "Error: Invalid subrange '$range'" >&2
 			usage
-			exit $ERR_VARGS
+			exit $err_vargs
 		fi
 		IFS="-"
-		SUBRANGE=(${RANGE[@]})
-		TFILES[${#TFILES[@]}]=$(mktemp)
+		subrange=(${range[@]})
+		tfiles[${#tfiles[@]}]=$(mktemp)
 		IFS=" "
-		eval $COMMAND -dFirstPage=${SUBRANGE[0]} -dLastPage=${SUBRANGE[-1]} -sOutputFile="${TFILES[-1]}" "$IN"
+		eval $command -dFirstPage=${subrange[0]} -dLastPage=${subrange[-1]} -sOutputFile="${tfiles[-1]}" "$in"
 	done
-	catpdf ${TFILES[@]} "$OUT"
-	rm ${TFILES[@]}
+	catpdf ${tfiles[@]} "$out"
+	rm ${tfiles[@]}
 }
 
 chkargs "$@"
diff --git a/imgur b/imgur
--- a/imgur
+++ b/imgur
@@ -14,12 +14,12 @@
 # revised --
 ##
 
-ERR_NARGS=3
-ERR_VARGS=5
+err_nargs=3
+err_vargs=5
 
-APIKEY="4f22353fbb8473a442bf708ecd553ffb"
+apikey="4f22353fbb8473a442bf708ecd553ffb"
 
-HFILE="$HOME/bin/.imgur_history"
+hfile="$HOME/bin/.imgur_history"
 
 usage()
 {
@@ -34,44 +34,44 @@ chkargs()
 		then
 			echo "Error: Too few arguments" >&2
 			usage
-			exit $ERR_NARGS
+			exit $err_nargs
 		else
 			echo "Error: Too many arguments" >&2
 			usage
-			exit $ERR_NARGS
+			exit $err_nargs
 		fi
 	elif [ ! -f "$1" ]
 	then
 		echo "Error: Invalid file '$1'" >&2
 		usage
-		exit $ERR_VARGS
+		exit $err_vargs
 	else
-		IMAGE="$1"
+		image="$1"
 	fi
 }
 
 ##----MAIN----##
 chkargs "$@"
 
-RESPONSE=$(curl -sF "key=$APIKEY" -F "image=@$IMAGE" http://imgur.com/api/upload.xml)
+response=$(curl -sF "key=$apikey" -F "image=@$image" http://imgur.com/api/upload.xml)
 
 if [ $? -ne 0 ]
 then
 	echo "Upload failed" >&2
 	exit 1
-elif [ $(grep -c "<error_msg>" <<< $RESPONSE) -gt 0 ]
+elif [ $(grep -c "<error_msg>" <<< $response) -gt 0 ]
 then
 	echo "Error: imgur says:" >&2
-	echo $RESPONSE | sed -r 's/.*<error_msg>(.*)<\/error_msg>.*/\1/' >&2
+	echo $response | sed -r 's/.*<error_msg>(.*)<\/error_msg>.*/\1/' >&2
 	exit 1
 fi
 
-IURL=$(sed -r 's/.*<original_image>(.*)<\/original_image>.*/\1/' <<< $RESPONSE)
-DURL=$(sed -r 's/.*<delete_page>(.*)<\/delete_page>.*/\1/' <<< $RESPONSE)
+iurl=$(sed -r 's/.*<original_image>(.*)<\/original_image>.*/\1/' <<< $response)
+durl=$(sed -r 's/.*<delete_page>(.*)<\/delete_page>.*/\1/' <<< $response)
 
-echo -n "$IURL" | xclip
-date +%T\ on\ %D >> $HFILE
-echo "$IURL" | tee -a $HFILE
-echo "$DURL" >> $HFILE
+echo -n "$iurl" | xclip
+date +%T\ on\ %D >> $hfile
+echo "$iurl" | tee -a $hfile
+echo "$durl" >> $hfile
 
 exit 0
diff --git a/wcshot b/wcshot
--- a/wcshot
+++ b/wcshot
@@ -16,12 +16,12 @@
 # revised --
 ##
 
-ERR_NARGS=3
-ERR_VARGS=5
+err_nargs=3
+err_vargs=5
 
-COMMAND="mplayer"
-COPTION="-msglevel all=-1:cplayer=-1:statusline=-1 -vf screenshot"
-VDEVICE="tv:// -tv driver=v4l2:width=640:height=480:device=/dev/video0"
+command="mplayer"
+coption="-msglevel all=-1:cplayer=-1:statusline=-1 -vf screenshot"
+vdevice="tv:// -tv driver=v4l2:width=640:height=480:device=/dev/video0"
 
 usage()
 {
@@ -40,16 +40,16 @@ chkargs()
 	then
 		echo "Error: Too many arguments" >&2
 		usage
-		exit $ERR_NARGS
+		exit $err_nargs
 	elif [ ! -z $1 ] && [ ! $(grep [[:digit:]]x[[:digit:]] <<< $1) ]
 	then
 		echo "Error: Invalid resolution" >&2
 		usage
-		exit $ERR_VARGS
+		exit $err_vargs
 	elif [ ! -z $1 ]
 	then
-		VDEVICE=${VDEVICE/640/$(cut -d x -f 1 <<< $1)}
-		VDEVICE=${VDEVICE/480/$(cut -d x -f 2 <<< $1)}
+		vdevice=${vdevice/640/$(cut -d x -f 1 <<< $1)}
+		vdevice=${vdevice/480/$(cut -d x -f 2 <<< $1)}
 	fi
 }
 
@@ -62,6 +62,6 @@ echo "Press s to take a shot, or S to start/stop taking continuous shots" >&2
 echo "Shots will be saved in current directory as shotNNNN.png" >&2
 echo
 echo "Press q to quit" >&2
-$COMMAND $COPTION $VDEVICE &> /dev/null || echo "Error: Mplayer crashed" >&2 && exit 1
+$command $coption $vdevice &> /dev/null || echo "Error: Mplayer crashed" >&2 && exit 1
 
 exit 0
