Style changes.

diff --git a/esplit b/esplit
--- a/esplit
+++ b/esplit
@@ -1,17 +1,14 @@
 #!/bin/bash
 
 ##
-# esplit -- split a file into pieces
+# esplit	-- split a file into pieces
 #
-# usage -- esplit -m | -c COUNT [FILE ...]
+# usage		-- esplit -m | -c COUNT FILE...
 #
-# written -- 27 May, 2009 by Egan McComb
+# written	-- 27 May, 2009 by Egan McComb
 #
-# revised -- 12 July, 2009 by author
+# revised	-- 12 July, 2009 by author
 ##
-
-err_nargs=3
-err_vargs=5
 
 size=16777216
 
@@ -22,29 +19,24 @@ usage()
 
 chkargs()
 {
-	if [ $# -lt 2 ]
+	if (( $# < 2 ))
 	then
 		echo "Error: Too few arguments" >&2
 		usage
-		exit $err_nargs
-	elif [ ! $1 = "-m" ] && [ ! $1 = "-c" ]
+		exit $ERR_NARGS
+	elif [[  $1 != "-m" ]] && [[ ! $1 = "-c" ]]
 	then
 		echo "Error: Invalid argument '$1'" >&2
 		usage
-		exit $err_vargs
+		exit $ERR_VARGS
 	fi
 }
 
 chkfile()
 {
-	if [ ! -e "$1" ]
+	if [[ ! -f "$1" ]]
 	then
-		echo "Error: Nonexistant file '$1'" >&2
-		echo "Skipping..." >&2
-		continue
-	elif [ ! -f "$1" ]
-	then
-		echo "Error: Bad file '$1'" >&2
+		echo "Error: Invalid file '$1'" >&2
 		echo "Skipping..." >&2
 		continue
 	fi
@@ -52,25 +44,25 @@ chkfile()
 
 methodc()
 {
-	if [ "$1" = "-m" ]
+	if [[ $1 = "-m" ]]
 	then
 		method=magic
 		nshift=shift
 	else
 		method=nsplit
-		if [ -z "$2" ]
+		if [[ -z "$2" ]]
 		then
 			echo "Error: Too few arguments" >&2
 			usage
-			exit $err_nargs
+			exit $ERR_NARGS
 		elif $(grep -q [^[:digit:]] <<< $2)
 		then
-			echo "Error: Invalid argument '$2'" >&2
+			echo "Error: Invalid size '$2'" >&2
 			usage
-			exit $err_vargs
+			exit $ERR_VARGS
 		else
 			method="nsplit $2"
-			nshift="shift && shift"
+			nshift="shift; shift"
 		fi
 	fi
 }
@@ -84,7 +76,7 @@ magic()
 
 nsplit()
 {
-	fsize=$(command ls -l "$2" | cut -d " " -f 5)
+	fsize=$(stat -c %s "$2")
 	ssize=$(($fsize/$1))
 	split -b $ssize "$2" "$2".
 	echo "Split file $2 into $1 pieces of $ssize bytes"
@@ -97,7 +89,7 @@ $nshift
 for file in "$@"
 do
 	chkfile "$file"
-	$METHOD "$file"
+	$method "$file"
 done
 
 exit 0
