Add check for Internet connectivity (netbool.sh)

diff --git a/gweather b/gweather
--- a/gweather
+++ b/gweather
@@ -72,6 +72,12 @@ chkargs()
 }
 
 ##----MAIN---##
+if ! netbool.sh
+then
+	echo "Error: Internet connectivity poor" >&2
+	exit 1
+fi
+
 chkargs "$@"
 qurl="http://www.google.com/ig/api?weather=$locid"
 curl -s "$qurl" | convert | xsltproc $filter - | check
